// <auto-generated />
namespace OgloszeniaDrobne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CategoryAtrributeDict : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoryAtrributeDict));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201536328_Category+Atrribute+Dict"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
